### ISSUE TITLE
gui.exe doesnot start

### ISSUE THREAD

**Issue by maidana97** [albertopasqualetto/Bulk-WhatsappWeb-Sender#42]
Hi, BWWBS-GUI-2.1.2 doesn't start, I run it but just open a cmd window for a few seconds and then it closes automatically

**Comment by albertopasqualetto** [comment]
Hello, you have to help me a little bit with troubleshooting.
Are you on windows? 
Is your system at 64bit?
Have you installed python and node js?
If you type winget upgrade on powershell, does it return something?

**Comment by maidana97** [comment]
I just installed node js, it's working now, thanks!

**Comment by albertopasqualetto** [comment]
Great!

May you please tell me if the command `winget upgrade` gives you an error or works in terminal? So I can improve this case handling.
(I am assuming you are on Windows)

**Comment by maidana97** [comment]
Windows Terminal Microsoft.WindowsTerminal 1.12.10983.0 1.16.10261.0 winget
1 update available.
Yes on Windows 11

**Comment by albertopasqualetto** [comment]
Thanks, I am closing this issue since I am not figuring out what did not work for you based on these info.
